// export const ROLES_SCOPE = 'ROLES_SCOPE';
// export const LISTING_SCOPE = 'LISTING_SCOPE';
export const SETTINGS_SCOPE = 'SETTINGS_SCOPE';
// export const SIMS_TYPES_SCOPE = 'SIMS_TYPES_SCOPE';

// export const SIM_SCOPE = 'SIM_SCOPE';
// export const SIMS_SCOPE = 'SIMS_SCOPE';
// export const SIM_NEW_SCOPE = 'SIM_NEW_SCOPE';
// export const SIM_EDIT_SCOPE = 'SIM_EDIT_SCOPE';
// export const SIMS_LIST_SCOPE = 'SIMS_LIST_SCOPE';
// export const SIM_AGENT_EDIT_SCOPE = 'SIM_AGENT_EDIT_SCOPE';
// export const SIM_COMPANY_EDIT_SCOPE = 'SIM_COMPANY_EDIT_SCOPE';
// export const SIM_OPERATOR_EDIT_SCOPE = 'SIM_OPERATOR_EDIT_SCOPE';

// export const ZONE_SCOPE = 'ZONE_SCOPE';
// export const ZONES_SCOPE = 'ZONES_SCOPE';
// export const ZONE_NEW_SCOPE = 'ZONE_NEW_SCOPE';
// export const ZONE_EDIT_SCOPE = 'ONE_EDIT_SCOPE';
// export const ZONES_AGENTS_SCOPE = 'ZONES_AGENTS_SCOPE';
// export const ZONES_ADD_AGENTS_SCOPE = 'ZONES_ADD_AGENTS_SCOPE';
// export const ZONES_COLLECTORS_SCOPE = 'ZONES_COLLECTORS_SCOPE';
// export const ZONES_ADD_COLLECTORS_SCOPE = 'ZONES_ADD_COLLECTORS_SCOPE';

// export const FLEET_SCOPE = 'FLEET_SCOPE';
// export const FLEETS_SCOPE = 'FLEETS_SCOPE';
// export const FLEET_NEW_SCOPE = 'FLEET_NEW_SCOPE';
// export const FLEET_EDIT_SCOPE = 'FLEET_EDIT_SCOPE';
// export const FLEET_ADD_SUPPLY_SCOPE = 'FLEET_ADD_SUPPLY_SCOPE';

// export const CLEARANCE_SCOPE = 'CLEARANCE_SCOPE';
// export const CLEARANCES_SCOPE = 'CLEARANCES_SCOPE';
// export const CLEARANCE_NEW_SCOPE = 'CLEARANCE_NEW_SCOPE';
// export const CLEARANCE_PROCEED_SCOPE = 'CLEARANCE_PROCEED_SCOPE';

export const LOGIN_SCOPE = 'LOGIN_SCOPE';
export const PROFILE_SCOPE = 'PROFILE_SCOPE';
export const PROFILE_AVATAR_SCOPE = 'PROFILE_AVATAR_SCOPE';
export const PROFILE_PASSWORD_SCOPE = 'PROFILE_PASSWORD_SCOPE';

export const AGENT_SCOPE = 'AGENT_SCOPE';
// export const AGENTS_SCOPE = 'AGENTS_SCOPE';
// export const AGENT_NEW_SCOPE = 'AGENT_NEW_SCOPE';
// export const AGENT_EDIT_SCOPE = 'AGENT_EDIT_SCOPE';
// export const AGENT_CNI_EDIT_SCOPE = 'AGENT_CNI_EDIT_SCOPE';
// export const AGENT_ADD_SIMS_SCOPE = 'AGENT_ADD_SIMS_SCOPE';
// export const AGENT_FILE_EDIT_SCOPE = 'AGENT_FILE_EDIT_SCOPE';

export const COMPANY_SCOPE = 'COMPANY_SCOPE';
// export const COMPANIES_SCOPE = 'COMPANIES_SCOPE';
// export const COMPANY_NEW_SCOPE = 'COMPANY_NEW_SCOPE';
// export const COMPANY_EDIT_SCOPE = 'COMPANY_EDIT_SCOPE';
// export const COMPANY_ADD_SIMS_SCOPE = 'COMPANY_ADD_SIMS_SCOPE';

export const USER_SCOPE = 'USER_SCOPE';
// export const USERS_SCOPE = 'USERS_SCOPE';
// export const USER_NEW_SCOPE = 'USER_NEW_SCOPE';
export const USER_EDIT_SCOPE = 'USER_EDIT_SCOPE';
export const USER_BALANCE_SCOPE = 'USER_BALANCE_SCOPE';
// export const USER_ROLE_EDIT_SCOPE = 'USER_ROLE_EDIT_SCOPE';
// export const USER_ZONE_EDIT_SCOPE = 'USER_ZONE_EDIT_SCOPE';

export const COLLECTOR_SCOPE = 'COLLECTOR_SCOPE';
// export const COLLECTORS_SCOPE = 'COLLECTORS_SCOPE';
// export const COLLECTOR_NEW_SCOPE = 'COLLECTOR_NEW_SCOPE';
// export const COLLECTOR_EDIT_SCOPE = 'COLLECTOR_EDIT_SCOPE';
// export const COLLECTOR_ADD_SIMS_SCOPE = 'COLLECTOR_EDIT_SCOPE';

export const OPERATOR_SCOPE = 'OPERATOR_SCOPE';
// export const OPERATORS_SCOPE = 'OPERATORS_SCOPE';
// export const OPERATOR_NEW_SCOPE = 'OPERATOR_NEW_SCOPE';
// export const OPERATOR_EDIT_SCOPE = 'OPERATOR_EDIT_SCOPE';
// export const OPERATOR_ADD_SIMS_SCOPE = 'OPERATOR_ADD_SIMS_SCOPE';

// export const REFUELS_SCOPE = 'REFUELS_SCOPE';
// export const AFFORDS_SCOPE = 'AFFORDS_SCOPE';
// export const SUPPLIES_SCOPE = 'SUPPLIES_SCOPE';
// export const ANONYMOUS_SCOPE = 'ANONYMOUS_SCOPE';
// export const TRANSFERS_SCOPE = 'TRANSFERS_SCOPE';
// export const SUPPLY_NEW_SCOPE = 'SUPPLY_NEW_SCOPE';
// export const REFUEL_NEW_SCOPE = 'REFUEL_NEW_SCOPE';
// export const AFFORD_NEW_SCOPE = 'AFFORD_NEW_SCOPE';
// export const TRANSFER_NEW_SCOPE = 'TRANSFER_NEW_SCOPE';
// export const ANONYMOUS_NEW_SCOPE = 'ANONYMOUS_NEW_SCOPE';

// export const OUTLAYS_SCOPE = 'OUTLAYS_SCOPE';
// export const PAYMENTS_SCOPE = 'PAYMENTS_SCOPE';
// export const HANDOVERS_SCOPE = 'HANDOVERS_SCOPE';
// export const OUTLAY_NEW_SCOPE = 'OUTLAY_NEW_SCOPE';
// export const PAYMENT_NEW_SCOPE = 'PAYMENT_NEW_SCOPE';
// export const HANDOVER_NEW_SCOPE = 'HANDOVER_NEW_SCOPE';

// export const CASH_RECOVERIES_SCOPE = 'CASH_RECOVERIES_SCOPE';
// export const FLEETS_RECOVERIES_SCOPE = 'FLEETS_RECOVERIES_SCOPE';
// export const CASH_RECOVERY_NEW_SCOPE = 'CASH_RECOVERY_NEW_SCOPE';
// export const FLEETS_RECOVERY_NEW_SCOPE = 'FLEETS_RECOVERY_NEW_SCOPE';

// export const NOTIFICATIONS_SCOPE = 'NOTIFICATIONS_SCOPE';
// export const UNREAD_NOTIFICATIONS_SCOPE = 'UNREAD_NOTIFICATIONS_SCOPE';
