// Cards
export const CARD_BALANCE = 2;
export const CARD_FLEETS_REQUESTS_MTN = 4;
export const CARD_FLEET_SIMS_FLEETS_MTN = 0;
export const CARD_FLEETS_REQUESTS_ORANGE = 7;
export const CARD_CLEARANCES_REQUEST_MTN = 6;
export const CARD_FLEET_SIMS_FLEETS_ORANGE = 3;
export const CARD_CLEARANCES_REQUEST_ORANGE = 1;

// Labels
export const LABEL_BALANCE = "SOLDE ESPECES";
export const LABEL_FLEET_SIMS_FLEETS_MTN = "SOLDE FLOTTE MTN";
export const LABEL_FLEETS_REQUESTS_MTN = "DEMANDES DE FLOTTES MTN";
export const LABEL_FLEET_SIMS_FLEETS_ORANGE = "SOLDE FLOTTE ORANGE";
export const LABEL_FLEETS_REQUESTS_ORANGE = "DEMANDES DE FLOTTES ORANGE";
export const LABEL_CLEARANCES_REQUEST_MTN = "DEMANDES DE DESTOCKAGES MTN";
export const LABEL_CLEARANCES_REQUEST_ORANGE = "DEMANDES DE DESTOCKAGES ORANGE";



