// Cards
export const CARD_AGENTS = 1;
export const CARD_BALANCE = 2;
export const CARD_RESOURCES = 3;
export const CARD_FLEETS_REQUESTS = 4;
export const CARD_FLEET_SIMS_FLEETS = 5;
export const CARD_CLEARANCES_REQUEST = 6;

// Labels
export const LABEL_AGENTS = "AGENTS";
export const LABEL_RESOURCES = "RESSOURCES";
export const LABEL_BALANCE = "SOLDE ESPECES";
export const LABEL_FLEETS_REQUESTS = "DEMANDES DE FLOTTES";
export const LABEL_CLEARANCES_REQUEST = "DEMANDES DE DESTOCKAGES";
export const LABEL_FLEET_SIMS_FLEETS = "FLOTTES PUCES DE FLOTTAGES";
