// Cards
export const CARD_SIMS = 4;
export const CARD_AGENTS = 3;
export const CARD_BALANCE = 0;
export const CARD_FLEETS_REQUESTS = 2;
export const CARD_FLEET_SIMS_FLEETS = 1;
export const CARD_CLEARANCES_REQUEST = 5;

// Charts
export const CHART_SIMS_PER_TYPES = 1;
export const CHART_FLEETS_REQUEST_PER_STATUS = 0;
export const CHART_CLEARANCES_REQUEST_PER_STATUS = 2;

// Labels
export const LABEL_AGENTS = 3;
export const LABEL_SIMS = "NOMBRE DES SIMS";
export const LABEL_BALANCE = "MON SOLDE ESPECES";
export const LABEL_FLEETS_REQUESTS = "NOMBRE DES DEMANDES DE FLOTTES";
export const LABEL_FLEET_SIMS_FLEETS = "TOTAL FLOTTES PUCES DE FLOTTAGES";
export const LABEL_CLEARANCES_REQUEST = "NOMBRE DES DEMANDES DE DESTOCKAGE";
