import React from 'react';

export const UserContext = React.createContext();
export const SimsContext = React.createContext();
export const UsersContext = React.createContext();
export const RolesContext = React.createContext();
export const ZonesContext = React.createContext();
export const ToastContext = React.createContext();
export const FleetsContext = React.createContext();
export const ErrorsContext = React.createContext();
export const AgentsContext = React.createContext();
export const RefuelsContext = React.createContext();
export const OutlaysContext = React.createContext();
export const RequestsContext = React.createContext();
export const DispatchContext = React.createContext();
export const SuppliesContext = React.createContext();
export const PaymentsContext = React.createContext();
export const AnonymousContext = React.createContext();
export const OperatorsContext = React.createContext();
export const CompaniesContext = React.createContext();
export const SimsTypesContext = React.createContext();
export const TransfersContext = React.createContext();
export const HandoversContext = React.createContext();
export const CollectorsContext = React.createContext();
export const ClearancesContext = React.createContext();
export const RecoveriesContext = React.createContext();
export const NotificationsContext = React.createContext();
